version: "3.8"

services:
  database:
    image: postgres:14.1-alpine
    container_name: blinker-pg-database
    restart: always
    ports:
      - ${PG_PORT}:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - pgdata:/data/postgres

  testing-database:
    image: postgres:14.1-alpine
    container_name: blinker-pg-database-test
    restart: always
    ports:
      - ${PG_TESTING_PORT}:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_TESTING_DB}
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine3.17
    container_name: blinker-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - ${REDIS_PORT}:6379
    network_mode: bridge
    restart: on-failure

volumes:
  pgdata:
